In [3]:
import numpy as np
arr1 = np.arange(0, 10, 3)
print("Array using arange:", arr1)



Array using arange: [0 3 6 9]


In [5]:
arr2 = np.linspace(0, 2, 5)
print("Array using linspace:", arr2)


Array using linspace: [0.  0.5 1.  1.5 2. ]


In [10]:
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)
print("Flattened version:", arr3.flatten())

Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [12]:
data = np.array([[5, 87, 9], [2, 4, 6]])

print("Original Data:\n", data)

Original Data:
 [[ 5 87  9]
 [ 2  4  6]]


In [13]:
print("Sum of all elements:", np.sum(data))
print("Column-wise sum:", np.sum(data, axis=0))
print("Row-wise mean:", np.mean(data, axis=1))
print("Max value:", np.max(data))


Sum of all elements: 113
Column-wise sum: [ 7 91 15]
Row-wise mean: [33.66666667  4.        ]
Max value: 87


In [14]:
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))
print("Standard Deviation:", np.std(data))

Index of max value (flattened): 1
Min value: 2
Standard Deviation: 30.558232205995747


In [16]:
a = np.array([3, 1, 8, 2, 9])
print("Original Array:", a)


Original Array: [3 1 8 2 9]


In [17]:
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)
idx = np.where(a > 5)
print("Indices where value > 5:", idx)
print("Values > 5:", a[idx])


Sorted Array: [1 2 3 8 9]
Indices where value > 5: (array([2, 4]),)
Values > 5: [8 9]


In [18]:
A = np.array([[11, 27], [23, 45]])
B = np.array([16, 23])
print("Matrix A:\n", A)
print("Vector B:", B)


Matrix A:
 [[11 27]
 [23 45]]
Vector B: [16 23]


In [19]:
C = A + B
print("Broadcasted Addition Result:\n", C)

Broadcasted Addition Result:
 [[27 50]
 [39 68]]


In [22]:
nums = np.array([1, 2, 3, 4, 5,6])
mask = nums > 4
print("Mask (nums > 4):", mask)



Mask (nums > 4): [False False False False  True  True]


In [23]:
filtered = nums[mask]
print("Filtered values:", filtered)
result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)




Filtered values: [5 6]
Even or Odd: ['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']


In [25]:
arr_orig = np.array([10, 20, 30,22,33,44])
arr_view = arr_orig[:]
arr_view[4] = 99
print("Original After View Change:", arr_orig)



Original After View Change: [10 20 30 22 99 44]


In [26]:
arr_copy = arr_orig.copy()
arr_copy[0] = 55
print("Original After Copy Change:", arr_orig)
print("Copy:", arr_copy)


Original After Copy Change: [10 20 30 22 99 44]
Copy: [55 20 30 22 99 44]


In [27]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
v_stack = np.vstack((x, y))
print("Vertical Stack:\n", v_stack)


Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [28]:
h_stack = np.hstack((x, y))
print("Horizontal Stack:\n", h_stack)
z = np.arange(10)
split_arr = np.array_split(z, 3)
print("Split into 3 parts:", split_arr)

Horizontal Stack:
 [1 2 3 4 5 6]
Split into 3 parts: [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [30]:
rand_ints = np.random.randint(0, 1001, size=(3, 3))
print("Random Integers:\n", rand_ints)
rand_norm = np.random.randn(2, 4)
print("Random Normal Distribution:\n", rand_norm)


Random Integers:
 [[ 60 753 615]
 [706 535 706]
 [430 423 671]]
Random Normal Distribution:
 [[-1.83946824  0.37782535  1.57042608  0.49457416]
 [-0.75483804  0.10445002  0.86490159  0.47443862]]


In [33]:
choices = np.random.choice([1, 3, 5,4,2,6, 7], size=8)
print("Random Choices:", choices)
np.random.seed(428)
print("Seeded Random Number:", np.random.rand())

Random Choices: [7 5 3 2 1 2 3 5]
Seeded Random Number: 0.8184240812247612


In [34]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original 1D Array:", arr)
print("Element at index 0:", arr[0])
print("Element at last index:", arr[-1])

Original 1D Array: [10 20 30 40 50 60]
Element at index 0: 10
Element at last index: 60


In [35]:
print("Slice from index 1 to 4:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])


Slice from index 1 to 4: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [37]:
matrix = np.array([[15, 2, 35],
                   [4, 57, 6],
                   [74, 8, 99]])

print("Original Matrix:\n", matrix)
print("Element at (1,2):", matrix[1, 2])
print("First row:", matrix[0, :])
print("Second column:", matrix[:, 1])
print("Top-left 2x2 block:\n", matrix[:2, :2])

Original Matrix:
 [[15  2 35]
 [ 4 57  6]
 [74  8 99]]
Element at (1,2): 6
First row: [15  2 35]
Second column: [ 2 57  8]
Top-left 2x2 block:
 [[15  2]
 [ 4 57]]


In [38]:
arr = np.array([5, 10, 15, 20,556,54,66,77, 25, 30])
mask = arr > 15
print("Boolean Mask:", mask)
print("Values greater than 15:", arr[mask])
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])


Boolean Mask: [False False False  True  True  True  True  True  True  True]
Values greater than 15: [ 20 556  54  66  77  25  30]
Even numbers > 10: [ 20 556  54  66  30]
