In [1]:
import pandas as pd
import numpy as np
print("--- Intermediate Pandas Exercise ---")
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")
# 1.1 Create a Pandas Series named 's1_1' from a list of numbers [10, 20, 30, 40, 50].
s1_1=pd.Series([10,20,30,40,50])
print(s1_1)
# 1.2 Create a 3x4 NumPy array named 'np_array1_2' with random integers between 1 and 100.
np_array1_2=np.random.randint(1,100,(3,4))
print(np_array1_2)
# 1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3' with columns 'A', 'B', 'C', 'D'.
df1_3=pd.DataFrame(np_array1_2,columns=['A','B','C','D'])
print(df1_3)


--- Intermediate Pandas Exercise ---

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
0    10
1    20
2    30
3    40
4    50
dtype: int64
[[59 20  9 26]
 [89  9 32 40]
 [80 40  6 59]]
    A   B   C   D
0  59  20   9  26
1  89   9  32  40
2  80  40   6  59


In [6]:
import numpy as np
import pandas as pd

# 1. Generate exactly 100 rows of dates using periods=100
date_range = pd.date_range(start='2023-01-01', periods=100, freq='D')

# 2. Create the DataFrame with uniform lowercase or title case column names
df_sales = pd.DataFrame({
    'Date': date_range,
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
    'Sales': np.random.randint(100, 1001, 100), # 1000 inclusive requires upper bound 1001
    'Quantity': np.random.randint(1, 11, 100)    # 10 inclusive requires upper bound 11
})

# 3. Introduce NaN values using distinct indices to prevent overlapping overwrites
nan_sales_idx = np.random.choice(df_sales.index, 5, replace=False)
nan_quant_idx = np.random.choice(df_sales.index, 3, replace=False)

df_sales.loc[nan_sales_idx, 'Sales'] = np.nan
df_sales.loc[nan_quant_idx, 'Quantity'] = np.nan

print("\n--- Task 2: Synthetic Data Generation for Practice ---")
print(df_sales.head(10))  # Previewing first 10 rows
print(df_sales.isna().sum())  # Verifying the exact count of NaN values



--- Task 2: Synthetic Data Generation for Practice ---
        Date Region   Product  Sales  Quantity
0 2023-01-01  North  Keyboard  963.0       9.0
1 2023-01-02  South   Monitor  574.0       1.0
2 2023-01-03   West   Monitor  182.0       9.0
3 2023-01-04   West     Mouse  390.0      10.0
4 2023-01-05  South    Laptop  269.0       8.0
5 2023-01-06  North   Monitor  417.0       6.0
6 2023-01-07  North   Monitor  785.0       3.0
7 2023-01-08   East     Mouse  681.0       2.0
8 2023-01-09  South    Laptop  253.0       4.0
9 2023-01-10   West     Mouse  813.0      10.0
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64


In [8]:
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
# Use 'df_sales' from Task 2.
Task2_df=df_sales
# 3.1 Select only the 'Region' and 'Sales' columns. Store it in 'df3_1'.
df3_1=Task2_df[['Region','Sales']]
print(df3_1)
# 3.2 Select rows where 'Product' is 'Laptop'. Store it in 'df3_2'.
df3_2=Task2_df[Task2_df['Product']=='Laptop']
print(df3_2)
# 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500. Store it in 'df3_3'.
df3_3=Task2_df[(Task2_df['Region']=='East')&(Task2_df['Sales']>500)]
print(df3_3)
# 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor' (use .loc and .iloc). Store it in 'val3_4'.
val3_4=Task2_df.loc[Task2_df['Product']=='Monitor','Sales'].iloc[0]
print(val3_4)


--- Task 3: Indexing and Slicing in DataFrames ---
   Region  Sales
0   North  963.0
1   South  574.0
2    West  182.0
3    West  390.0
4   South  269.0
..    ...    ...
95   West  222.0
96   East  460.0
97  North  113.0
98  South  869.0
99   West  611.0

[100 rows x 2 columns]
         Date Region Product  Sales  Quantity
4  2023-01-05  South  Laptop  269.0       8.0
8  2023-01-09  South  Laptop  253.0       4.0
13 2023-01-14   East  Laptop  504.0       6.0
17 2023-01-18  South  Laptop  208.0       1.0
21 2023-01-22   East  Laptop  276.0       NaN
28 2023-01-29   East  Laptop  692.0       7.0
31 2023-02-01   West  Laptop  573.0       7.0
36 2023-02-06  North  Laptop  137.0       1.0
43 2023-02-13  South  Laptop  595.0       9.0
44 2023-02-14  South  Laptop  190.0       1.0
45 2023-02-15  North  Laptop  673.0       4.0
49 2023-02-19  North  Laptop  563.0       7.0
58 2023-02-28   West  Laptop  645.0       1.0
64 2023-03-06   East  Laptop  999.0      10.0
66 2023-03-08  North  Laptop  

In [9]:
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
# Use 'df_sales' from Task 2 (which should have NaNs).
Task2_dfdf=df_sales
# 4.1 Check how many missing values are in each column. Store the result in 'missing_counts4_1'.
missing_counts4_1=Task2_df.isna().sum()
print(missing_counts4_1)
# 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column. Store the modified DataFrame in 'df4_2_filled'.
df4_2_filled=Task2_df.copy()
df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean(),inplace=True)
print(df4_2_filled)
# 4.3 Drop rows that have any missing values in 'df_sales'. Store the result in 'df4_3_dropped'.
df4_3_dropped=Task2_df.dropna()
print(df4_3_dropped)


--- Task 4: Data Cleaning (Handling Missing Values) ---
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64
         Date Region   Product  Sales  Quantity
0  2023-01-01  North  Keyboard  963.0       9.0
1  2023-01-02  South   Monitor  574.0       1.0
2  2023-01-03   West   Monitor  182.0       9.0
3  2023-01-04   West     Mouse  390.0      10.0
4  2023-01-05  South    Laptop  269.0       8.0
..        ...    ...       ...    ...       ...
95 2023-04-06   West   Monitor  222.0       3.0
96 2023-04-07   East     Mouse  460.0       9.0
97 2023-04-08  North   Monitor  113.0       1.0
98 2023-04-09  South     Mouse  869.0       4.0
99 2023-04-10   West   Monitor  611.0       9.0

[100 rows x 5 columns]
         Date Region   Product  Sales  Quantity
0  2023-01-01  North  Keyboard  963.0       9.0
1  2023-01-02  South   Monitor  574.0       1.0
2  2023-01-03   West   Monitor  182.0       9.0
3  2023-01-04   West     Mouse  390.0      10.0
4  2023-01-05  South

/tmp/ipykernel_855/3123802303.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean(),inplace=True)


In [10]:
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
# Use 'df_sales' (the original one with NaNs)
df_sales=Task2_df
# 5.1 Create a new column 'Total_Revenue' which is 'Sales' * 'Quantity'.
df_sales['Total_Revenue']=df_sales['Sales']*df_sales['Quantity']
print(df_sales)
#     (Be mindful of NaNs, the result should also be NaN where either Sales or Quantity is NaN).

# 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order. Store it in 'df5_2_sorted'.
df5_2_sorted=df_sales.sort_values(by=['Date','Sales'],ascending=[True,False])
print(df5_2_sorted)
# 5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity' for each region.
df5_3_grouped_region=df_sales.groupby('Region')[['Sales','Quantity']].sum()
print(df5_3_grouped_region)
#     Store the result in 'df5_3_grouped_region'.
df5_3_grouped_region=df_sales.groupby('Region')[['Sales','Quantity']].sum()
print(df5_3_grouped_region)
# 5.4 Group 'df_sales' by 'Product' and find the average 'Sales' for each product.
df5_4_grouped_product=df_sales.groupby('Product')['Sales'].mean()
print(df5_4_grouped_product.mean())
#     Store the result in 'df5_4_grouped_product'.
df5_4_grouped_product=df_sales.groupby('Product')['Sales'].mean()
print(df5_4_grouped_product.mean())


--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---
         Date Region   Product  Sales  Quantity  Total_Revenue
0  2023-01-01  North  Keyboard  963.0       9.0         8667.0
1  2023-01-02  South   Monitor  574.0       1.0          574.0
2  2023-01-03   West   Monitor  182.0       9.0         1638.0
3  2023-01-04   West     Mouse  390.0      10.0         3900.0
4  2023-01-05  South    Laptop  269.0       8.0         2152.0
..        ...    ...       ...    ...       ...            ...
95 2023-04-06   West   Monitor  222.0       3.0          666.0
96 2023-04-07   East     Mouse  460.0       9.0         4140.0
97 2023-04-08  North   Monitor  113.0       1.0          113.0
98 2023-04-09  South     Mouse  869.0       4.0         3476.0
99 2023-04-10   West   Monitor  611.0       9.0         5499.0

[100 rows x 6 columns]
         Date Region   Product  Sales  Quantity  Total_Revenue
0  2023-01-01  North  Keyboard  963.0       9.0         8667.0
1  2023-01-02  South   Monitor